import { User } from './user.model';

export const USERS: User[] = [
  {
    username: 'admin',
    fullName: 'Alice Nguyen',
    email: 'alice.nguyen@example.com',
    phone: '+84 912 345 678',
    role: 'Admin',
    gender: 'Female',
    status: 'Active',
    initials: 'AN',
  },
  {
    username: 'teacher1',
    fullName: 'Minh Tran',
    email: 'minh.tran@example.com',
    phone: '+84 912 345 679',
    role: 'Teacher',
    gender: 'Male',
    status: 'Active',
    initials: 'MT',
  },
  {
    username: 'student1',
    fullName: 'Lan Hoang',
    email: 'lan.hoang@example.com',
    phone: '+84 912 345 680',
    role: 'Student',
    gender: 'Female',
    status: 'Active',
    initials: 'LH',
  },
  {
    username: 'student2',
    fullName: 'Tuan Le',
    email: 'tuan.le@example.com',
    phone: '+84 912 345 681',
    role: 'Student',
    gender: 'Male',
    status: 'Inactive',
    initials: 'TL',
  },
  {
    username: 'teacher2',
    fullName: 'Hien Pham',
    email: 'hien.pham@example.com',
    phone: '+84 912 345 682',
    role: 'Teacher',
    gender: 'Other',
    status: 'Active',
    initials: 'HP',
  },
];
